#!/bin/sh

start() {
    echo "Start App"
    sh /usr/bin/app-hu/starter.sh
}

stop() {
    echo "Kill App"
    sh /usr/bin/app-hu/killer.sh
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    *)
        echo "Usage: /etc/init.d/app_auto {start|stop}"
        exit 1
        ;;
esac

exit 0

